# Generated by Django 5.1.1 on 2024-10-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("make", models.CharField(max_length=128)),
                ("model", models.CharField(max_length=128)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("make", ""), _negated=True),
                            models.Q(("model", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="non_empty_camera",
                    ),
                    models.UniqueConstraint(
                        fields=("make", "model"), name="unique_camera"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="unique_file_type")
                ],
            },
        ),
        migrations.CreateModel(
            name="Lens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("make", models.CharField(max_length=128)),
                ("model", models.CharField(max_length=128)),
                (
                    "position",
                    models.IntegerField(
                        choices=[(0, "back camera"), (1, "front camera")], null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lenses",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("make", ""), _negated=True),
                            models.Q(("model", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="non_empty_lens",
                    ),
                    models.UniqueConstraint(
                        fields=("make", "model"), name="unique_lens"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MimeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="unique_mime_type")
                ],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("thumbnail", models.FileField(upload_to="")),
                ("file_name", models.CharField(max_length=256)),
                ("file_path", models.CharField(max_length=4096)),
                ("is_image", models.BooleanField(null=True)),
                ("is_video", models.BooleanField(null=True)),
                ("file_size", models.PositiveBigIntegerField()),
                ("file_atime", models.DateTimeField()),
                ("file_mtime", models.DateTimeField()),
                ("file_ctime", models.DateTimeField()),
                ("image_width", models.PositiveIntegerField(null=True)),
                ("image_height", models.PositiveIntegerField(null=True)),
                ("megapixels", models.FloatField(null=True)),
                ("taken_on", models.DateTimeField(null=True)),
                ("gps_latitude", models.FloatField(null=True)),
                ("gps_longitude", models.FloatField(null=True)),
                ("gps_altitude", models.FloatField(null=True)),
                ("metadata", models.JSONField()),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photos.camera",
                    ),
                ),
                (
                    "file_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photos.filetype",
                    ),
                ),
                (
                    "lens",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photos.lens",
                    ),
                ),
                (
                    "mime_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photos.mimetype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("file_path",), name="unique_photo_file_path"
                    )
                ],
            },
        ),
    ]
